name: Publish package (crates.io)

on:
  workflow_call:
    inputs:
      rust-toolchain:
        description: The Rust toolchain
        default: ${{vars.RUST_TOOLCHAIN || 'stable'}}
        type: string
      path:
        description: crate path
        default: "."
        type: string
    secrets:
      CARGO_REGISTRY_TOKEN:
        description: An authentication token for crates.io
        required: true

jobs:
  package:
    name: Publish Rust package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{inputs.rust-toolchain}}
      - name: Publish to crates.io
        working-directory: ${{inputs.path}}
        env:
          CARGO_REGISTRY_TOKEN: ${{secrets.CARGO_REGISTRY_TOKEN}}
        run: |
          cargo publish
